#!/bin/bash

# Check if the Gnome Shell extension is enabled or not, and why.
gnome-extensions info gnome-night-light-slider@kyleabaker.github.com

# GNOME Shell logs
journalctl /usr/bin/gnome-shell -f
